# Site Settings
title: Blogger
email: joweber123@gmail.com
description: >
  James's blog
baseurl: /blogger
url: "http://localhost:4000/blogger"

github_username: joweber123
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']


kramdown:
  input: GFM
gems: [jekyll-assets, autoprefixer-rails]
